# Generated by Django 6.0.6 on 2026-08-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_student_dni'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('grade', 'name', 'year')},
        ),
        migrations.AlterField(
            model_name='section',
            name='letter',
            field=models.CharField(default='-', max_length=50, verbose_name='Letra'),
        ),
    ]
