from .catalog_views import catalog_view
from .loan_views import request_material_view, teacher_loans_view
from .dispatch_views import dispatch_panel_view, update_loan_status_view
from .inventory_views import inventory_panel_view, edit_material_view, delete_material_view