# Generated by Django 6.0.6 on 2026-06-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('event_date', models.DateField(verbose_name='Fecha del Evento')),
                ('is_holiday', models.BooleanField(default=False, verbose_name='Es feriado')),
            ],
            options={
                'verbose_name': 'Evento Institucional',
                'verbose_name_plural': 'Eventos Institucionales',
                'ordering': ['event_date'],
            },
        ),
    ]
