# Generated by Django 6.0.6 on 2026-06-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_institutionalevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación Lógica'), ('HARD_DELETE', 'Eliminación Física'), ('RESTORE', 'Restauración')], max_length=15, verbose_name='Acción'),
        ),
    ]
