# Generated by Django 6.0.6 on 2026-07-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación Lógica'), ('HARD_DELETE', 'Eliminación Física'), ('RESTORE', 'Restauración'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('PERMISSIONS', 'Cambio de Permisos')], max_length=15, verbose_name='Acción'),
        ),
    ]
