# Generated by Django 6.0.6 on 2026-08-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalnotification',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Enlace'),
        ),
    ]
