# Generated by Django 6.0.8 on 2026-09-03 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_internalnotification_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Contenido')),
                ('image', models.ImageField(blank=True, null=True, upload_to='institutional_announcements/%Y/%m/', verbose_name='Imagen')),
                ('audience', models.CharField(choices=[('ALL', 'Docentes y apoderados'), ('TEACHERS', 'Solo docentes'), ('PARENTS', 'Solo apoderados')], default='ALL', max_length=10, verbose_name='Destinatarios')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Visible hasta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Publicado por')),
            ],
            options={
                'verbose_name': 'Comunicado institucional',
                'verbose_name_plural': 'Comunicados institucionales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de lectura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_acknowledgements', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='core.institutionalannouncement', verbose_name='Comunicado')),
            ],
            options={
                'verbose_name': 'Constancia de lectura',
                'verbose_name_plural': 'Constancias de lectura',
                'ordering': ['-acknowledged_at'],
                'constraints': [models.UniqueConstraint(fields=('announcement', 'user'), name='unique_announcement_acknowledgement')],
            },
        ),
    ]
