# Generated by Django 6.0.8 on 2026-09-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_institutionalannouncement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionalannouncement',
            name='event_date',
            field=models.DateField(blank=True, help_text='Fecha del evento anunciado, si corresponde.', null=True, verbose_name='Fecha relacionada'),
        ),
    ]
