# Generated by Django 6.0.8 on 2026-09-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación Lógica'), ('HARD_DELETE', 'Eliminación Física'), ('RESTORE', 'Restauración'), ('LOGIN', 'Inicio de Sesión'), ('LOGIN_BLOCKED', 'Acceso bloqueado'), ('RESET_REQUEST', 'Solicitud de recuperación'), ('RESET_BLOCKED', 'Recuperación bloqueada'), ('PASSWORD_RESET', 'Contraseña recuperada'), ('ADMIN_RESET', 'Restablecimiento administrativo'), ('LOGOUT', 'Cierre de Sesión'), ('PERMISSIONS', 'Cambio de Permisos')], max_length=15, verbose_name='Acción'),
        ),
    ]
