# Generated by Django 6.0.6 on 2026-07-17 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Categoría')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría Documental',
                'verbose_name_plural': 'Categorías Documentales',
            },
        ),
        migrations.CreateModel(
            name='InstitutionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('title', models.CharField(max_length=255, verbose_name='Título del Documento')),
                ('access_level', models.CharField(choices=[('PUBLIC', 'Público (Toda la comunidad)'), ('STAFF', 'Interno (Solo Personal)'), ('DIRECTIVE', 'Confidencial (Solo Directivos)')], default='STAFF', max_length=20, verbose_name='Nivel de Acceso')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='Etiquetas (separadas por coma)')),
                ('current_file', models.FileField(upload_to='institutional_docs/', verbose_name='Archivo Actual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documentcategory')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Institucional',
                'verbose_name_plural': 'Documentos Institucionales',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='institutional_docs/versions/', verbose_name='Archivo Histórico')),
                ('version_number', models.PositiveIntegerField(verbose_name='Número de Versión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('change_summary', models.CharField(blank=True, max_length=255, null=True, verbose_name='Resumen de cambios')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.institutionaldocument')),
            ],
            options={
                'verbose_name': 'Versión de Documento',
                'verbose_name_plural': 'Versiones de Documentos',
                'ordering': ['-version_number'],
            },
        ),
    ]
