# Generated by Django 6.0.6 on 2026-06-12 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock Actual')),
                ('unit', models.CharField(max_length=50, verbose_name='Unidad de medida')),
                ('state', models.CharField(max_length=50, verbose_name='Estado físico')),
                ('location', models.CharField(max_length=100, verbose_name='Ubicación en almacén')),
                ('cycle', models.CharField(max_length=50, verbose_name='Ciclo')),
                ('pedagogical_use', models.TextField(blank=True, null=True, verbose_name='Uso pedagógico')),
                ('manual', models.FileField(blank=True, null=True, upload_to='manuals/', verbose_name='Manual opcional')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('DISPATCHED', 'Despachado'), ('RETURNED', 'Devuelto'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Préstamo',
                'verbose_name_plural': 'Solicitudes de Préstamo',
            },
        ),
        migrations.CreateModel(
            name='LoanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField(verbose_name='Cantidad solicitada')),
                ('quantity_returned', models.PositiveIntegerField(default=0, verbose_name='Cantidad devuelta')),
                ('quantity_waste', models.PositiveIntegerField(default=0, verbose_name='Merma / Dañados')),
                ('loan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='warehouse.loanrequest')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.material')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='materials/', verbose_name='Imagen')),
                ('is_main', models.BooleanField(default=False, verbose_name='Es imagen principal')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='warehouse.material')),
            ],
        ),
    ]
