# Generated by Django 6.0.6 on 2026-06-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='required_for',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Requerido para'),
        ),
    ]
