# Generated by Django 6.0.6 on 2026-06-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_loanrequest_required_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='expected_return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Devolución esperada'),
        ),
    ]
