# Generated by Django 6.0.6 on 2026-07-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_loanrequest_deleted_at_loanrequest_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.CharField(default='General', max_length=100, verbose_name='Categoría'),
        ),
    ]
