# Generated by Django 6.0.6 on 2026-06-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='support_role',
            field=models.CharField(blank=True, help_text='Ej: Psicólogo, Auxiliar, Encargado de Almacén', max_length=50, null=True, verbose_name='Cargo Específico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DIRECTOR', 'Director'), ('SUBDIRECTOR', 'Subdirector'), ('DOCENTE', 'Docente'), ('APOYO', 'Personal de Apoyo'), ('APODERADO', 'Apoderado'), ('SUPERUSER', 'Superuser Técnico')], max_length=20, verbose_name='Rol'),
        ),
    ]
