# Generated by Django 6.0.6 on 2026-06-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_support_role_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='module_permissions',
            field=models.JSONField(blank=True, default=list, verbose_name='Permisos de Módulos'),
        ),
    ]
