# Generated by Django 6.0.6 on 2026-07-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_module_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='support_role',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cargo Específico'),
        ),
    ]
