# Generated by Django 6.0.8 on 2026-09-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_loginthrottle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginthrottle',
            name='scope',
            field=models.CharField(choices=[('ACCOUNT', 'Cuenta'), ('IP', 'Dirección IP'), ('RESET_ACC', 'Recuperación por cuenta'), ('RESET_IP', 'Recuperación por IP')], max_length=10, verbose_name='Ámbito'),
        ),
    ]
