# Generated by Django 6.0.6 on 2026-06-12 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('LEVE', 'Leve'), ('MODERADA', 'Moderada'), ('GRAVE', 'Grave')], max_length=10, verbose_name='Gravedad')),
                ('subtype', models.CharField(choices=[('CONDUCTA', 'Conducta'), ('RENDIMIENTO', 'Rendimiento'), ('SALUD', 'Salud'), ('ASISTENCIA', 'Asistencia')], max_length=15, verbose_name='Subtipo')),
                ('description', models.TextField(verbose_name='Descripción de los hechos')),
                ('date_reported', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reporte')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='academics.student', verbose_name='Alumno')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='discipline_evidences/', verbose_name='Archivo de evidencia')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='discipline.incident')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
            },
        ),
    ]
