# Generated by Django 6.0.8 on 2026-09-15 21:16

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def migrate_historical_incidents(apps, schema_editor):
    Incident = apps.get_model('discipline', 'Incident')
    mapping = {
        'CONDUCTA': ('CONDUCTA_INADECUADA', 'CONDUCTA_DISRUPTIVA'),
        'RENDIMIENTO': ('RIESGO_SITUACION_ESPECIAL', 'REQUIERE_SEGUIMIENTO'),
        'SALUD': ('RIESGO_SITUACION_ESPECIAL', 'OTRO'),
        'ASISTENCIA': ('DANO_INCUMPLIMIENTO', 'INCUMPLIMIENTO_NORMA'),
    }
    for incident in Incident.objects.select_related('student__section').all():
        previous_subtype = incident.subtype
        category, subtype = mapping.get(
            previous_subtype,
            ('RIESGO_SITUACION_ESPECIAL', 'OTRO'),
        )
        incident.legacy_subtype = previous_subtype
        incident.category = category
        incident.subtype = subtype
        incident.occurred_at = incident.date_reported
        incident.location = 'OTRO'
        incident.other_location = 'No registrado en la ficha histórica'
        incident.academic_year = incident.student.section.year
        incident.code = f'INC-{incident.academic_year}-{incident.pk:06d}'
        incident.save(update_fields=[
            'legacy_subtype', 'category', 'subtype', 'occurred_at', 'location',
            'other_location', 'academic_year', 'code',
        ])


def restore_historical_subtypes(apps, schema_editor):
    Incident = apps.get_model('discipline', 'Incident')
    for incident in Incident.objects.exclude(legacy_subtype=''):
        incident.subtype = incident.legacy_subtype
        incident.save(update_fields=['subtype'])


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_section_unique_together_alter_section_letter'),
        ('discipline', '0002_incident_deleted_at_incident_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='academic_year',
            field=models.PositiveIntegerField(editable=False, null=True, verbose_name='Año académico'),
        ),
        migrations.AddField(
            model_name='incident',
            name='additional_observations',
            field=models.TextField(blank=True, verbose_name='Observaciones adicionales'),
        ),
        migrations.AddField(
            model_name='incident',
            name='additional_people',
            field=models.TextField(blank=True, verbose_name='Otras personas involucradas'),
        ),
        migrations.AddField(
            model_name='incident',
            name='additional_students',
            field=models.ManyToManyField(blank=True, related_name='secondary_incidents', to='academics.student', verbose_name='Estudiantes adicionales'),
        ),
        migrations.AddField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('CONDUCTA_INADECUADA', 'Conducta inadecuada'), ('AGRESION', 'Agresión'), ('ACOSO_INTIMIDACION', 'Acoso o intimidación'), ('DANO_INCUMPLIMIENTO', 'Daño o incumplimiento de normas'), ('RIESGO_SITUACION_ESPECIAL', 'Riesgo o situación especial')], default='CONDUCTA_INADECUADA', max_length=40, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='incident',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=24, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='incident',
            name='immediate_action',
            field=models.TextField(default='', verbose_name='Acción inmediata realizada'),
        ),
        migrations.AddField(
            model_name='incident',
            name='legacy_subtype',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='Clasificación histórica original'),
        ),
        migrations.AddField(
            model_name='incident',
            name='location',
            field=models.CharField(choices=[('AULA', 'Aula'), ('PATIO', 'Patio'), ('PASILLO', 'Pasillo'), ('SERVICIOS_HIGIENICOS', 'Servicios higiénicos'), ('BIBLIOTECA', 'Biblioteca'), ('AREA_DEPORTIVA', 'Área deportiva'), ('INGRESO_SALIDA', 'Ingreso / salida'), ('OTRO', 'Otro')], default='AULA', max_length=30, verbose_name='Lugar'),
        ),
        migrations.AddField(
            model_name='incident',
            name='occurred_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de la incidencia'),
        ),
        migrations.AddField(
            model_name='incident',
            name='other_location',
            field=models.CharField(blank=True, max_length=120, verbose_name='Otro lugar'),
        ),
        migrations.AddField(
            model_name='incident',
            name='referred_to',
            field=models.CharField(blank=True, choices=[('TUTOR', 'Tutor'), ('DIRECCION', 'Dirección'), ('SUBDIRECCION', 'Subdirección'), ('PSICOPEDAGOGIA', 'Psicopedagogía')], max_length=30, verbose_name='Derivar a'),
        ),
        migrations.AddField(
            model_name='incident',
            name='requires_follow_up',
            field=models.BooleanField(default=False, verbose_name='Requiere seguimiento'),
        ),
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('REGISTRADA', 'Registrada'), ('EN_SEGUIMIENTO', 'En seguimiento'), ('CERRADA', 'Cerrada')], default='REGISTRADA', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='incident',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='subtype',
            field=models.CharField(choices=[('DESOBEDIENCIA', 'Desobediencia'), ('INTERRUPCION_REITERADA', 'Interrupción reiterada'), ('FALTA_RESPETO', 'Falta de respeto'), ('CONDUCTA_DISRUPTIVA', 'Conducta disruptiva'), ('OTRO', 'Otro'), ('FISICA', 'Física'), ('VERBAL', 'Verbal'), ('AMENAZA', 'Amenaza'), ('BURLAS_REITERADAS', 'Burlas reiteradas'), ('HOSTIGAMIENTO', 'Hostigamiento'), ('EXCLUSION_DELIBERADA', 'Exclusión deliberada'), ('CIBERACOSO', 'Ciberacoso'), ('DANO_BIENES', 'Daño a bienes'), ('SUSTRACCION_PERTENENCIAS', 'Sustracción de pertenencias'), ('OBJETO_PROHIBIDO', 'Uso de objeto prohibido'), ('ZONA_RESTRINGIDA', 'Ingreso a zona restringida'), ('INCUMPLIMIENTO_NORMA', 'Incumplimiento de norma'), ('CONDUCTA_PELIGROSA', 'Conducta peligrosa'), ('ACCIDENTE', 'Accidente'), ('CRISIS_EMOCIONAL', 'Crisis emocional'), ('REQUIERE_SEGUIMIENTO', 'Situación que requiere seguimiento')], max_length=40, verbose_name='Subtipo'),
        ),
        migrations.RunPython(
            migrate_historical_incidents,
            restore_historical_subtypes,
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['category', 'subtype'], name='incident_category_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['severity', 'occurred_at'], name='incident_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['academic_year', 'status'], name='incident_year_status_idx'),
        ),
    ]
