# Generated by Django 6.0.8 on 2026-09-15 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_section_unique_together_alter_section_letter'),
        ('discipline', '0003_incident_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='academics.student', verbose_name='Alumno'),
        ),
    ]
