# Generated by Django 6.0.6 on 2026-06-12 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('TRABAJO', 'Ficha de Trabajo'), ('TAREA', 'Ficha de Tarea')], max_length=10, verbose_name='Tipo de Ficha')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('file', models.FileField(upload_to='portfolio_files/', verbose_name='Archivo adjunto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Ficha de Portafolio',
                'verbose_name_plural': 'Fichas de Portafolio',
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Observación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de observación')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='made_observations', to=settings.AUTH_USER_MODEL, verbose_name='Director')),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='portfolio.portfolioitem')),
            ],
            options={
                'verbose_name': 'Observación Directiva',
                'verbose_name_plural': 'Observaciones Directivas',
            },
        ),
    ]
