# Generated by Django 6.0.6 on 2026-07-20 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('portfolio', '0002_portfolioitem_deleted_at_portfolioitem_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='academics.section', verbose_name='Sección'),
        ),
    ]
